import { fireEvent, render, screen } from "@testing-library/react";
import { axe } from "jest-axe";
import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("next/link", () => ({
  default: ({ children, href, ...props }: React.ComponentProps<"a">) => (
    <a href={href} {...props}>{children}</a>
  ),
}));

import { Feed } from "@/components/social/feed";

describe("Feed", { timeout: 15_000 }, () => {
  beforeEach(() => {
    Object.defineProperty(window, "innerWidth", {
      configurable: true,
      value: 390,
    });
  });

  it("renders the community feed at a mobile viewport", () => {
    render(<Feed />);

    expect(screen.getByRole("heading", { name: "Community" })).toBeVisible();
    expect(screen.getByRole("tab", { name: "For you" })).toHaveAttribute("aria-selected", "true");
    expect(screen.getByRole("tab", { name: "Following" })).toHaveAttribute("aria-selected", "false");
    expect(screen.getByRole("combobox", { name: "Filter feed by category" })).toHaveValue("");
    expect(screen.getByRole("link", { name: "Share a win" })).toHaveAttribute("href", "/tasks");
    expect(screen.getAllByRole("article").length).toBeGreaterThan(0);
    expect(screen.getByRole("button", { name: "Show more progress" })).toBeVisible();
  });

  it("visibly labels AI follower posts and generated content", () => {
    render(<Feed />);

    expect(screen.getAllByText("AI").length).toBeGreaterThan(0);
    expect(screen.getByText("Moss").nextElementSibling).toHaveTextContent(/^AI$/);
    expect(screen.getAllByText("AI-generated").length).toBeGreaterThan(0);
    expect(
      screen.getAllByText("This post was generated by an AI follower.").length,
    ).toBeGreaterThan(0);
  });

  it("visibly identifies AI follower likes", () => {
    render(<Feed />);

    expect(screen.getAllByText(/\d+ AI/).length).toBeGreaterThan(0);
  });

  it("offers only Like and Reply as post actions", () => {
    render(<Feed />);

    expect(screen.getAllByRole("button", { name: /Like/ })).toHaveLength(20);
    expect(screen.getAllByRole("button", { name: /^Reply/ })).toHaveLength(20);
    expect(screen.queryByRole("button", { name: /Cheer|Respect|Relatable|Inspired/ })).not.toBeInTheDocument();
  });

  it("replaces the old preview posts with AI task completions", () => {
    render(<Feed />);

    expect(screen.getAllByText("Completed a task")).toHaveLength(20);
    expect(screen.queryByText("Mina Park")).not.toBeInTheDocument();
    expect(screen.queryByText("Jonah Lee")).not.toBeInTheDocument();
  });

  it("exposes reaction state with aria-pressed", () => {
    render(<Feed />);
    const like = screen.getAllByRole("button", { name: /Like/ })[0];

    expect(like).toHaveAttribute("aria-pressed", "false");
    fireEvent.click(like);

    expect(like).toHaveAttribute("aria-pressed", "true");
  });

  it("announces a saved reaction to assistive technology", () => {
    render(<Feed />);
    const like = screen.getAllByRole("button", { name: /Like/ })[0];

    fireEvent.click(like);

    expect(screen.getByText("Like saved.")).toBeInTheDocument();
  });

  it("posts a reply from the primary Reply action", () => {
    render(<Feed />);
    fireEvent.click(screen.getAllByRole("button", { name: /^Reply/ })[0]);
    const input = screen.getByLabelText("Reply to Moss");

    fireEvent.change(input, { target: { value: "Nice progress." } });
    fireEvent.submit(input.closest("form")!);

    expect(screen.getByText("Reply posted. Preview only.")).toBeInTheDocument();
    expect(screen.getByText("Nice progress.")).toBeVisible();
  });

  it("shows posts from the user's chosen interests in Following", () => {
    render(<Feed />);
    fireEvent.click(screen.getByRole("tab", { name: "Following" }));

    expect(screen.getByRole("tab", { name: "Following" })).toHaveAttribute("aria-selected", "true");
    expect(screen.getAllByRole("article")).toHaveLength(4);
    expect(screen.getByText("North")).toBeVisible();
    expect(screen.getByText("Pixel")).toBeVisible();
    expect(screen.getByText("Nova Reyes")).toBeVisible();
    expect(screen.getByText("Barnaby Wisp")).toBeVisible();
    expect(screen.queryByText("Moss")).not.toBeInTheDocument();
  });

  it("lets users filter either feed by one of their categories", () => {
    render(<Feed />);

    fireEvent.change(screen.getByRole("combobox", { name: "Filter feed by category" }), {
      target: { value: "Fitness" },
    });

    expect(screen.getAllByRole("article")).toHaveLength(1);
    expect(screen.getByText("North")).toBeVisible();
    expect(screen.getByText("Category: Fitness")).toBeVisible();
  });

  it("links generated posts to the correct AI profile", () => {
    render(<Feed />);

    expect(screen.getByRole("link", { name: "Nova Reyes" })).toHaveAttribute("href", "/companions/nova-reyes");
    expect(screen.getByRole("link", { name: "Brother Alden" })).toHaveAttribute("href", "/companions/brother-alden");
  });

  it("supports arrow-key navigation between feed tabs", () => {
    render(<Feed />);
    const communityTab = screen.getByRole("tab", { name: "For you" });

    communityTab.focus();
    fireEvent.keyDown(communityTab, { key: "ArrowRight" });

    expect(screen.getByRole("tab", { name: "Following" })).toHaveAttribute("aria-selected", "true");
  });

  it("has no automated accessibility violations", async () => {
    const { container } = render(<Feed />);

    expect(await axe(container)).toHaveNoViolations();
  });
});
