import { fireEvent, render, screen, within } from "@testing-library/react";
import { axe } from "jest-axe";
import { beforeEach, describe, expect, it, vi } from "vitest";

const push = vi.hoisted(() => vi.fn());

vi.mock("next/link", () => ({
  default: ({ children, href, ...props }: React.ComponentProps<"a">) => (
    <a href={href} {...props}>{children}</a>
  ),
}));
vi.mock("next/navigation", () => ({ useRouter: () => ({ push }) }));

import { Feed, previewFeed } from "@/components/social/feed";

describe("Feed", { timeout: 15_000 }, () => {
  beforeEach(() => {
    push.mockReset();
    Object.defineProperty(window, "innerWidth", {
      configurable: true,
      value: 390,
    });
  });

  it("renders the community feed at a mobile viewport", () => {
    render(<Feed />);

    expect(screen.getByRole("heading", { name: "Community" })).toBeVisible();
    expect(screen.getByRole("tab", { name: "For you" })).toHaveAttribute("aria-selected", "true");
    expect(screen.getByRole("tab", { name: "Following" })).toHaveAttribute("aria-selected", "false");
    expect(screen.getByRole("tab", { name: "People only" })).toHaveAttribute("aria-selected", "false");
    expect(screen.getByRole("combobox", { name: "Filter feed by category" })).toHaveValue("");
    expect(screen.queryByRole("region", { name: "Share progress" })).not.toBeInTheDocument();
    expect(screen.queryByText("What did you make progress on?")).not.toBeInTheDocument();
    expect(screen.getAllByRole("article").length).toBeGreaterThan(0);
    expect(screen.queryByRole("region", { name: "Community progress" })).not.toBeInTheDocument();
    expect(screen.queryByText("Happening now")).not.toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Show more posts" })).toBeVisible();
  });

  it("identifies AI follower posts without redundant disclosures", () => {
    render(<Feed />);

    expect(screen.getAllByText("AI").length).toBeGreaterThan(0);
    expect(screen.getByText("Moss").nextElementSibling).toHaveTextContent(/^AI$/);
    expect(screen.getByRole("article", { name: "Open post by Moss" })).not.toHaveClass("border-l-2", "border-l-community");
    expect(screen.queryByText("AI follower post")).not.toBeInTheDocument();
    expect(screen.queryByText("AI-generated")).not.toBeInTheDocument();
    expect(screen.queryByText("This post was generated by an AI follower.")).not.toBeInTheDocument();
  });

  it("visibly identifies AI follower likes", () => {
    render(<Feed />);

    expect(screen.getAllByText(/\d+ AI/).length).toBeGreaterThan(0);
  });

  it("attributes AI persona reposts on the original post", () => {
    render(<Feed />);

    expect(screen.getByText("Orbit reposted")).toBeVisible();
  });

  it("offers Like, Reply, and Repost as post actions", () => {
    render(<Feed />);

    expect(screen.getAllByRole("button", { name: /Like/ })).toHaveLength(previewFeed.length);
    expect(screen.getAllByRole("button", { name: /^Reply/ })).toHaveLength(previewFeed.length);
    expect(screen.getAllByRole("button", { name: /^Repost/ })).toHaveLength(previewFeed.length);
    expect(screen.queryByRole("button", { name: "View conversation" })).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /Cheer|Respect|Relatable|Inspired/ })).not.toBeInTheDocument();
  });

  it("reports AI posts from the top-right overflow menu", () => {
    render(<Feed />);

    const options = screen.getByRole("button", { name: "More actions for Moss" });
    expect(screen.getAllByRole("button", { name: /More actions for/ })).toHaveLength(previewFeed.length);
    expect(options).toHaveClass("post-menu-trigger");
    expect(options).not.toHaveClass("icon-btn", "rounded-full");
    expect(options).toHaveAttribute("aria-expanded", "false");

    fireEvent.click(options);

    expect(options).toHaveAttribute("aria-expanded", "true");
    fireEvent.click(screen.getByRole("menuitem", { name: "Report AI post" }));

    expect(screen.getByText("Post reported for review. Preview only.")).toBeVisible();
    expect(options).toHaveAttribute("aria-expanded", "false");
  });

  it("opens the conversation thread when the post is clicked", () => {
    render(<Feed />);

    const moss = previewFeed.find((post) => post.social_companions?.slug === "moss")!;
    fireEvent.click(screen.getByRole("article", { name: "Open post by Moss" }));

    expect(push).toHaveBeenCalledWith(`/posts/${encodeURIComponent(moss.id)}`);
  });

  it("keeps post controls independent from thread navigation", () => {
    render(<Feed />);

    fireEvent.click(screen.getAllByRole("button", { name: /Like/ })[0]);
    fireEvent.click(screen.getAllByRole("button", { name: /More actions for/ })[0]);

    expect(push).not.toHaveBeenCalled();
  });

  it("balances human progress with clearly labeled AI progress", () => {
    render(<Feed />);

    expect(screen.getAllByText("Completed a task")).toHaveLength(previewFeed.length);
    expect(screen.getByRole("article", { name: "Open post by Mina" })).toBeVisible();
    expect(screen.getByRole("article", { name: "Open post by Jonah" })).toBeVisible();
    expect(screen.getByRole("article", { name: "Open post by Moss" })).toBeVisible();
    expect(screen.getAllByText("AI").length).toBeLessThan(previewFeed.length);
  });

  it("keeps post content compact without shrinking the established type scale", () => {
    render(<Feed />);

    const post = screen.getByRole("article", { name: "Open post by Mina" });
    const content = within(post).getByText(/Sent the kickoff agenda/);
    const taskCard = within(post).getByText("Send the kickoff agenda").parentElement;
    const actions = within(post).getByLabelText("Post actions");
    const like = within(actions).getByRole("button", { name: /Like/ });
    const reply = within(actions).getByRole("button", { name: /^Reply/ });

    expect(post.firstElementChild).toHaveClass("p-4", "pb-0");
    expect(post.firstElementChild).not.toHaveClass("sm:p-5");
    expect(content).toHaveClass("mt-3", "text-[.98rem]", "leading-7");
    expect(taskCard).toHaveClass("mt-3", "p-3");
    expect(actions).toHaveClass("mt-2");
    expect(actions).not.toHaveClass("border-t", "border-line", "pt-2");
    expect(like).toHaveClass("post-action");
    expect(reply).toHaveClass("post-action");
  });

  it("lets owners change a post audience after sharing", () => {
    render(<Feed />);
    const post = screen.getByRole("article", { name: "Open post by Mina" });

    fireEvent.click(within(post).getByRole("button", { name: "More actions for Mina" }));
    fireEvent.click(screen.getByRole("menuitem", { name: "Make post private" }));

    expect(within(post).getByText("Private")).toBeVisible();
    expect(screen.getByText("Post is now private. Preview only.")).toBeVisible();
  });

  it("lets owners retract a shared post", () => {
    const confirm = vi.spyOn(window, "confirm").mockReturnValue(true);
    render(<Feed />);
    const post = screen.getByRole("article", { name: "Open post by Mina" });

    fireEvent.click(within(post).getByRole("button", { name: "More actions for Mina" }));
    fireEvent.click(screen.getByRole("menuitem", { name: "Delete post" }));

    expect(confirm).toHaveBeenCalledWith("Delete this post and its replies? This cannot be undone.");
    expect(screen.queryByRole("article", { name: "Open post by Mina" })).not.toBeInTheDocument();
    expect(screen.getByText("Post deleted. Preview only.")).toBeVisible();
    confirm.mockRestore();
  });

  it("exposes reaction state with aria-pressed", () => {
    render(<Feed />);
    const like = screen.getAllByRole("button", { name: /Like/ })[0];

    expect(like).toHaveAttribute("aria-pressed", "false");
    fireEvent.click(like);

    expect(like).toHaveAttribute("aria-pressed", "true");
  });

  it("optimistically toggles repost state and count in preview mode", () => {
    render(<Feed />);
    const repost = screen.getAllByRole("button", { name: /^Repost/ })[0];

    expect(repost).toHaveAttribute("aria-pressed", "false");
    expect(repost).toHaveTextContent("0");
    fireEvent.click(repost);

    expect(screen.getAllByRole("button", { name: /^Repost/ })[0]).toHaveAttribute("aria-pressed", "true");
    expect(screen.getAllByRole("button", { name: /^Repost/ })[0]).toHaveTextContent("1");
    expect(screen.getByText("Repost saved. Preview only.")).toBeInTheDocument();
  });

  it("announces a saved reaction to assistive technology", () => {
    render(<Feed />);
    const like = screen.getAllByRole("button", { name: /Like/ })[0];

    fireEvent.click(like);

    expect(screen.getByText("Like saved.")).toBeInTheDocument();
  });

  it("posts a reply from the primary Reply action", async () => {
    render(<Feed />);
    const mossPost = screen.getByRole("article", { name: "Open post by Moss" });
    fireEvent.click(within(mossPost).getByRole("button", { name: /^Reply/ }));
    const input = screen.getByLabelText("Reply to Moss");
    const composer = input.closest("form")!;

    expect(screen.queryByText("No replies yet. A thoughtful note can go a long way.")).not.toBeInTheDocument();
    const avatar = within(composer).getByRole("img", { name: "Mina Mori" });
    const submit = within(composer).getByRole("button", { name: "Reply" });
    expect(avatar).toBeVisible();
    expect(composer.firstElementChild).toBe(avatar);
    expect(composer.lastElementChild).toBe(submit);
    expect(input).toHaveAttribute("placeholder", "Post your reply");
    expect(submit).toBeDisabled();
    fireEvent.change(input, { target: { value: "Nice progress." } });
    expect(submit).toBeEnabled();
    fireEvent.submit(composer);

    expect(await screen.findByText("Reply posted. Preview only.")).toBeInTheDocument();
    expect(screen.getAllByRole("button", { name: /^Reply 1$/ })).toHaveLength(1);
    expect(screen.queryByText("Nice progress.")).not.toBeInTheDocument();
  });

  it("shows human and AI posts from the user's chosen interests", () => {
    render(<Feed />);
    fireEvent.click(screen.getByRole("tab", { name: "Following" }));

    expect(screen.getByRole("tab", { name: "Following" })).toHaveAttribute("aria-selected", "true");
    expect(screen.getAllByRole("article")).toHaveLength(7);
    expect(screen.getByText("Jonah")).toBeVisible();
    expect(screen.getByText("Aya")).toBeVisible();
    expect(screen.getByText("Priya")).toBeVisible();
    expect(screen.getByText("North")).toBeVisible();
    expect(screen.getByText("Pixel")).toBeVisible();
    expect(screen.getByText("Nova Reyes")).toBeVisible();
    expect(screen.getByText("Leo")).toBeVisible();
    expect(screen.queryByText("Moss")).not.toBeInTheDocument();
  });

  it("lets users filter either feed by one of their categories", () => {
    render(<Feed />);

    fireEvent.change(screen.getByRole("combobox", { name: "Filter feed by category" }), {
      target: { value: "Fitness" },
    });

    expect(screen.getAllByRole("article")).toHaveLength(2);
    expect(screen.getByText("Jonah")).toBeVisible();
    expect(screen.getByText("North")).toBeVisible();
    expect(screen.getByText("Category: Fitness")).toBeVisible();
  });

  it("offers a human-only feed without a pre-feed progress module", () => {
    render(<Feed />);
    fireEvent.click(screen.getByRole("tab", { name: "People only" }));

    expect(screen.getByRole("tab", { name: "People only" })).toHaveAttribute("aria-selected", "true");
    expect(screen.queryByRole("region", { name: "Community progress" })).not.toBeInTheDocument();
    expect(screen.getByRole("article", { name: "Open post by Mina" })).toBeVisible();
    expect(screen.getByRole("article", { name: "Open post by Jonah" })).toBeVisible();
    expect(screen.queryByRole("article", { name: "Open post by Moss" })).not.toBeInTheDocument();
    expect(screen.queryByText("AI")).not.toBeInTheDocument();
  });

  it("links generated posts to the correct AI profile", () => {
    render(<Feed />);

    expect(screen.getByRole("link", { name: "Nova Reyes" })).toHaveAttribute("href", "/companions/nova-reyes");
    expect(screen.getByRole("link", { name: "Pixel" })).toHaveAttribute("href", "/companions/pixel");
  });

  it("supports arrow-key navigation between feed tabs", () => {
    render(<Feed />);
    const communityTab = screen.getByRole("tab", { name: "For you" });

    communityTab.focus();
    fireEvent.keyDown(communityTab, { key: "ArrowRight" });

    expect(screen.getByRole("tab", { name: "Following" })).toHaveAttribute("aria-selected", "true");
  });

  it("has no automated accessibility violations", async () => {
    const { container } = render(<Feed />);

    expect(await axe(container)).toHaveNoViolations();
  });
});
