import { fireEvent, render, screen } from "@testing-library/react";
import { axe } from "jest-axe";
import { beforeEach, describe, expect, it, vi } from "vitest";

const push = vi.hoisted(() => vi.fn());

vi.mock("next/link", () => ({
  default: ({ children, href, ...props }: React.ComponentProps<"a">) => (
    <a href={href} {...props}>{children}</a>
  ),
}));
vi.mock("next/navigation", () => ({ useRouter: () => ({ push }) }));

import { Feed, previewFeed } from "@/components/social/feed";

describe("Feed", { timeout: 15_000 }, () => {
  beforeEach(() => {
    push.mockReset();
    Object.defineProperty(window, "innerWidth", {
      configurable: true,
      value: 390,
    });
  });

  it("renders the community feed at a mobile viewport", () => {
    render(<Feed />);

    expect(screen.getByRole("heading", { name: "Community" })).toBeVisible();
    expect(screen.getByRole("tab", { name: "For you" })).toHaveAttribute("aria-selected", "true");
    expect(screen.getByRole("tab", { name: "Following" })).toHaveAttribute("aria-selected", "false");
    expect(screen.getByRole("combobox", { name: "Filter feed by category" })).toHaveValue("");
    expect(screen.queryByRole("region", { name: "Share progress" })).not.toBeInTheDocument();
    expect(screen.queryByText("What did you make progress on?")).not.toBeInTheDocument();
    expect(screen.getAllByRole("article").length).toBeGreaterThan(0);
    expect(screen.getByRole("button", { name: "Show more progress" })).toBeVisible();
  });

  it("identifies AI follower posts without redundant disclosures", () => {
    render(<Feed />);

    expect(screen.getAllByText("AI").length).toBeGreaterThan(0);
    expect(screen.getByText("Moss").nextElementSibling).toHaveTextContent(/^AI$/);
    expect(screen.queryByText("AI follower post")).not.toBeInTheDocument();
    expect(screen.queryByText("AI-generated")).not.toBeInTheDocument();
    expect(screen.queryByText("This post was generated by an AI follower.")).not.toBeInTheDocument();
  });

  it("visibly identifies AI follower likes", () => {
    render(<Feed />);

    expect(screen.getAllByText(/\d+ AI/).length).toBeGreaterThan(0);
  });

  it("offers only Like and Reply as post actions", () => {
    render(<Feed />);

    expect(screen.getAllByRole("button", { name: /Like/ })).toHaveLength(20);
    expect(screen.getAllByRole("button", { name: /^Reply/ })).toHaveLength(20);
    expect(screen.queryByRole("button", { name: "View conversation" })).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /Cheer|Respect|Relatable|Inspired/ })).not.toBeInTheDocument();
  });

  it("reports AI posts from the top-right overflow menu", () => {
    render(<Feed />);

    const options = screen.getAllByRole("button", { name: /More actions for/ });
    expect(options).toHaveLength(20);
    expect(options[0]).toHaveAttribute("aria-expanded", "false");

    fireEvent.click(options[0]);

    expect(options[0]).toHaveAttribute("aria-expanded", "true");
    fireEvent.click(screen.getByRole("menuitem", { name: "Report AI post" }));

    expect(screen.getByText("Post reported for review. Preview only.")).toBeVisible();
    expect(options[0]).toHaveAttribute("aria-expanded", "false");
  });

  it("opens the conversation thread when the post is clicked", () => {
    render(<Feed />);

    fireEvent.click(screen.getByRole("article", { name: "Open post by Moss" }));

    expect(push).toHaveBeenCalledWith(`/posts/${encodeURIComponent(previewFeed[0].id)}`);
  });

  it("keeps post controls independent from thread navigation", () => {
    render(<Feed />);

    fireEvent.click(screen.getAllByRole("button", { name: /Like/ })[0]);
    fireEvent.click(screen.getAllByRole("button", { name: /More actions for/ })[0]);

    expect(push).not.toHaveBeenCalled();
  });

  it("replaces the old preview posts with AI task completions", () => {
    render(<Feed />);

    expect(screen.getAllByText("Completed a task")).toHaveLength(20);
    expect(screen.queryByText("Mina Park")).not.toBeInTheDocument();
    expect(screen.queryByText("Jonah Lee")).not.toBeInTheDocument();
  });

  it("exposes reaction state with aria-pressed", () => {
    render(<Feed />);
    const like = screen.getAllByRole("button", { name: /Like/ })[0];

    expect(like).toHaveAttribute("aria-pressed", "false");
    fireEvent.click(like);

    expect(like).toHaveAttribute("aria-pressed", "true");
  });

  it("announces a saved reaction to assistive technology", () => {
    render(<Feed />);
    const like = screen.getAllByRole("button", { name: /Like/ })[0];

    fireEvent.click(like);

    expect(screen.getByText("Like saved.")).toBeInTheDocument();
  });

  it("posts a reply from the primary Reply action", () => {
    render(<Feed />);
    fireEvent.click(screen.getAllByRole("button", { name: /^Reply/ })[0]);
    const input = screen.getByLabelText("Reply to Moss");

    expect(screen.queryByText("No replies yet. A thoughtful note can go a long way.")).not.toBeInTheDocument();
    fireEvent.change(input, { target: { value: "Nice progress." } });
    fireEvent.submit(input.closest("form")!);

    expect(screen.getByText("Reply posted. Preview only.")).toBeInTheDocument();
    expect(screen.getAllByRole("button", { name: /^Reply 1$/ })).toHaveLength(1);
    expect(screen.queryByText("Nice progress.")).not.toBeInTheDocument();
  });

  it("shows posts from the user's chosen interests in Following", () => {
    render(<Feed />);
    fireEvent.click(screen.getByRole("tab", { name: "Following" }));

    expect(screen.getByRole("tab", { name: "Following" })).toHaveAttribute("aria-selected", "true");
    expect(screen.getAllByRole("article")).toHaveLength(4);
    expect(screen.getByText("North")).toBeVisible();
    expect(screen.getByText("Pixel")).toBeVisible();
    expect(screen.getByText("Nova Reyes")).toBeVisible();
    expect(screen.getByText("Barnaby Wisp")).toBeVisible();
    expect(screen.queryByText("Moss")).not.toBeInTheDocument();
  });

  it("lets users filter either feed by one of their categories", () => {
    render(<Feed />);

    fireEvent.change(screen.getByRole("combobox", { name: "Filter feed by category" }), {
      target: { value: "Fitness" },
    });

    expect(screen.getAllByRole("article")).toHaveLength(1);
    expect(screen.getByText("North")).toBeVisible();
    expect(screen.getByText("Category: Fitness")).toBeVisible();
  });

  it("links generated posts to the correct AI profile", () => {
    render(<Feed />);

    expect(screen.getByRole("link", { name: "Nova Reyes" })).toHaveAttribute("href", "/companions/nova-reyes");
    expect(screen.getByRole("link", { name: "Brother Alden" })).toHaveAttribute("href", "/companions/brother-alden");
  });

  it("supports arrow-key navigation between feed tabs", () => {
    render(<Feed />);
    const communityTab = screen.getByRole("tab", { name: "For you" });

    communityTab.focus();
    fireEvent.keyDown(communityTab, { key: "ArrowRight" });

    expect(screen.getByRole("tab", { name: "Following" })).toHaveAttribute("aria-selected", "true");
  });

  it("has no automated accessibility violations", async () => {
    const { container } = render(<Feed />);

    expect(await axe(container)).toHaveNoViolations();
  });
});
