-- Minimal first-party product analytics for the public beta. Events contain
-- only identities, entity IDs, and timestamps: never task titles, completion
-- notes, chat messages, prompts, generated text, or other user content.

create table public.beta_product_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in (
    'session_active',
    'daily_active',
    'task_created',
    'task_completed',
    'completion_post_created',
    'persona_followed',
    'persona_unfollowed',
    'persona_favorited',
    'persona_unfavorited',
    'ai_like_completed',
    'ai_reply_completed',
    'ai_quote_completed',
    'persona_chat_message_sent'
  )),
  user_id uuid not null references auth.users(id) on delete cascade,
  companion_id uuid references public.social_companions(id) on delete set null,
  source_id uuid,
  event_date date not null,
  activity_bucket timestamptz,
  occurred_at timestamptz not null default now(),
  check ((event_name = 'session_active') = (activity_bucket is not null))
);

create unique index beta_product_events_source_unique
  on public.beta_product_events(event_name, source_id)
  where source_id is not null
    and event_name not in ('session_active', 'daily_active');
create unique index beta_product_events_daily_active_unique
  on public.beta_product_events(user_id, event_date)
  where event_name = 'daily_active';
create unique index beta_product_events_session_active_unique
  on public.beta_product_events(user_id, activity_bucket)
  where event_name = 'session_active';
create index beta_product_events_funnel_idx
  on public.beta_product_events(event_name, event_date, occurred_at);
create index beta_product_events_companion_idx
  on public.beta_product_events(companion_id, event_name, occurred_at)
  where companion_id is not null;

alter table public.beta_product_events enable row level security;
revoke all on public.beta_product_events from public, anon, authenticated;
grant all on public.beta_product_events to service_role;

create or replace function public.capture_beta_product_event(
  p_event_name text,
  p_user_id uuid,
  p_source_id uuid default null,
  p_companion_id uuid default null,
  p_occurred_at timestamptz default now(),
  p_activity_bucket timestamptz default null
) returns void
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.beta_product_events(
    event_name, user_id, companion_id, source_id, event_date,
    activity_bucket, occurred_at
  ) values (
    p_event_name, p_user_id, p_companion_id, p_source_id,
    (p_occurred_at at time zone 'UTC')::date,
    p_activity_bucket, p_occurred_at
  ) on conflict do nothing;
end $$;

-- Called only by the authenticated server route with its verified user ID.
-- The browser supplies neither an event name nor an event payload.
create or replace function public.record_beta_session_activity(p_user_id uuid)
returns void
language plpgsql security definer set search_path = '' as $$
declare
  observed_at timestamptz := clock_timestamp();
  bucket timestamptz;
begin
  bucket := to_timestamp(floor(extract(epoch from observed_at) / 1800) * 1800);
  perform public.capture_beta_product_event(
    'daily_active', p_user_id, null, null, observed_at, null
  );
  perform public.capture_beta_product_event(
    'session_active', p_user_id, null, null, observed_at, bucket
  );
end $$;

create or replace function public.capture_beta_task_event()
returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    perform public.capture_beta_product_event(
      'task_created', new.owner_id, new.id, null, new.created_at, null
    );
  elsif old.status <> 'completed' and new.status = 'completed' then
    perform public.capture_beta_product_event(
      'task_completed', new.owner_id, new.id, null,
      coalesce(new.completed_at, now()), null
    );
  end if;
  return new;
end $$;

create trigger beta_tasks_created
  after insert on public.tasks
  for each row execute function public.capture_beta_task_event();
create trigger beta_tasks_completed
  after update of status on public.tasks
  for each row execute function public.capture_beta_task_event();

create or replace function public.capture_beta_completion_post_event()
returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.kind = 'human_completion' and new.author_id is not null then
    perform public.capture_beta_product_event(
      'completion_post_created', new.author_id, new.id, null,
      new.created_at, null
    );
  end if;
  return new;
end $$;

create trigger beta_completion_posts_created
  after insert on public.social_posts
  for each row execute function public.capture_beta_completion_post_event();

create or replace function public.capture_beta_relationship_event()
returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  was_following boolean := false;
  was_favorite boolean := false;
begin
  if tg_op = 'UPDATE' then
    was_following := old.user_followed_at is not null;
    was_favorite := old.is_favorite;
  end if;

  if not was_following and new.user_followed_at is not null then
    perform public.capture_beta_product_event(
      'persona_followed', new.user_id, gen_random_uuid(), new.companion_id,
      new.user_followed_at, null
    );
  elsif was_following and new.user_followed_at is null then
    perform public.capture_beta_product_event(
      'persona_unfollowed', new.user_id, gen_random_uuid(), new.companion_id,
      now(), null
    );
  end if;

  if not was_favorite and new.is_favorite then
    perform public.capture_beta_product_event(
      'persona_favorited', new.user_id, gen_random_uuid(), new.companion_id,
      coalesce(new.favorited_at, now()), null
    );
  elsif was_favorite and not new.is_favorite then
    perform public.capture_beta_product_event(
      'persona_unfavorited', new.user_id, gen_random_uuid(), new.companion_id,
      now(), null
    );
  end if;
  return new;
end $$;

create trigger beta_persona_relationship_changed
  after insert or update of user_followed_at, is_favorite
  on public.user_companion_relationships
  for each row execute function public.capture_beta_relationship_event();

create or replace function public.capture_beta_ai_engagement_event()
returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  target_user uuid;
  captured_name text;
begin
  if old.state = 'completed' or new.state <> 'completed' then return new; end if;

  if new.target_reply_id is not null then
    select reply.author_id into target_user
    from public.social_replies reply where reply.id = new.target_reply_id;
  else
    select post.author_id into target_user
    from public.social_posts post where post.id = new.post_id;
  end if;
  if target_user is null then return new; end if;

  captured_name := case new.kind
    when 'reaction' then 'ai_like_completed'
    when 'reply' then 'ai_reply_completed'
    when 'quote' then 'ai_quote_completed'
  end;
  if captured_name is not null then
    perform public.capture_beta_product_event(
      captured_name, target_user, new.id, new.companion_id, now(), null
    );
  end if;
  return new;
end $$;

create trigger beta_ai_engagements_completed
  after update of state on public.social_ai_engagements
  for each row execute function public.capture_beta_ai_engagement_event();

create or replace function public.capture_beta_persona_chat_event()
returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  target_companion uuid;
begin
  if new.sender_user_id is null then return new; end if;
  select thread.companion_id into target_companion
  from public.chat_threads thread where thread.id = new.thread_id;
  if target_companion is not null then
    perform public.capture_beta_product_event(
      'persona_chat_message_sent', new.sender_user_id, new.id,
      target_companion, new.created_at, null
    );
  end if;
  return new;
end $$;

create trigger beta_persona_chat_messages_sent
  after insert on public.chat_messages
  for each row execute function public.capture_beta_persona_chat_event();

revoke all on function public.capture_beta_product_event(text,uuid,uuid,uuid,timestamptz,timestamptz),
  public.record_beta_session_activity(uuid),
  public.capture_beta_task_event(),
  public.capture_beta_completion_post_event(),
  public.capture_beta_relationship_event(),
  public.capture_beta_ai_engagement_event(),
  public.capture_beta_persona_chat_event()
  from public, anon, authenticated;
grant execute on function public.record_beta_session_activity(uuid) to service_role;

comment on table public.beta_product_events is
  'Server-only, content-free public beta product outcomes. Query with trusted administrative credentials only.';
comment on function public.record_beta_session_activity(uuid) is
  'Records deduplicated daily and 30-minute session activity for a server-verified user.';

notify pgrst, 'reload schema';
